### ISSUE TITLE
Error: noUiSlider: 'range' value isn't numeric.

### ISSUE THREAD

**Issue by gin93r** [vasyl-stanislavchuk/angular-nouislider#27]
Is there anyway to set the start and end other than hardcoding it into the attributes?

**Comment by gin93r** [comment]
It seems that following the instructions in [this issue](https://github.com/vasyabigi/angular-nouislider/issues/17) and using more parseFloats fixed the issue.

**Comment by pidupuis** [comment]
I have the same issue. Could you explain how you solved this ?

Thanks

**Comment by pidupuis** [comment]
Ok, I solved it.

In fact start and end params are defined with an @ in the scope:

``` js
scope: {
    start: '@',
    step: '@',
    end: '@',
    callback: '@',
    margin: '@',
    ngModel: '=',
    ngFrom: '=',
    ngTo: '='
},
```

So we simply need to surround variables with brackets as following:

``` html
<div slider ng-from="selection.min" ng-to="selection.max" start="{{ param.min }}" end="{{ param.max }}" step="{{ param.step }}"></div>
```

Maybe I missed it somewhere but this truly needs to be in the doc!

**Comment by gin93r** [comment]
Sorry, I just saw this message @pidupuis - glad you figured it out though. :)
