### ISSUE TITLE
Any plans to update nouislider to the latest version?

### ISSUE THREAD

**Issue by rathishcholarajan** [vasyl-stanislavchuk/angular-nouislider#35]
Hi,
This component is using version 6.x of nouislider. Any plans to add support for version 8.x of nouislider?

**Comment by Yankovsky** [comment]
@rathishc24 you can check my nouislider directive https://github.com/Yankovsky/nouislider-angular It supports latest version.

**Comment by rathishcholarajan** [comment]
@Yankovsky Thanks. I did consider your directive too while evaluating. Ended up implementing my own angular wrapper since we had to do some heavy customization.
