### ISSUE TITLE
Directive not compatible with latest 6.1.0 release

### ISSUE THREAD

**Issue by raphaelpflieger** [vasyl-stanislavchuk/angular-nouislider#6]
Thanks a lot for this directive, it's quite neat and I have already used it with success on a couple of projects.

Unfortunately it seems that it is not compatible with noUiSlider latest release. After updating my assets to support it, I get the following errors in Chrome WebDeveloper Tools:

```
Uncaught TypeError: undefined is not a function jquery.nouislider.js?body=1:1251
Error: noUiSlider: 'start' option is incorrect.
```

The "undefined is not a function" error is pointing at a conflict with this line added in the last release:

```
// Attach a classbased val handler.
$.classVal(Classes[0], 'vGet', 'vSet', false);
```

The error happened using the classic demo slider:

```
<div slider ng-from="test.from" ng-to="test.to" start=0 end=100 step=5 callback='set'></div>
```

Hope you will manage to figure it out easily... Thanks again !

**Comment by vasyl-stanislavchuk** [comment]
Updated directive to use last noUiSlider version.
